# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time


name: CICD Test1

on:
  push:
    branches: [ "main" ]


jobs:
  Job1-compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   # cloning git
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile package
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar
        
  Job2-trivy:
    runs-on: ubuntu-latest
    needs: Job1-compile

    steps:
    - uses: actions/checkout@v4   # cloning git

    - name: install trivy
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
    #- name: trivy scan
    #  run: trivy fs --format table -o trivy.json .
    - name: gitleaks install
      run: sudo apt install gitleaks -y
    - name: gitleaks scan
      run: gitleaks detect source . -r gl.json -f json .
  Job3-docker:
    runs-on: ubuntu-latest
    needs: Job2-trivy

    steps:
    - uses: actions/checkout@v4   # cloning git

   
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: app

 
