# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time


name: CICD Test1

on:
  push:
    branches: [ "main" ]


jobs:
  Job1-compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   # cloning git
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  Job2-trivy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   # cloning git

    - name: install trivy
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy
    - name: trivy scan
      run: trivy fs --format table -o trivy.json .
    - name: gitleaks install
      run: sudo apt install gitleaks -y
    - name: gitleaks scan
      run: gitleaks detect source . -r gl.json -f json .

 
